### ISSUE TITLE
visualization problem with ojs 3.3.0

### ISSUE THREAD

**Issue by weroiss** [nicolols/OJS-3-enhanced-advanced-search#2]
Hi, 
i'm new with ojs. I need to extend the advanced search, but with my ojs version I obtain a blank page only. 
In error.log I can see: 
[Wed Jul 28 09:19:22.200069 2021] [php:error] [pid 5188:tid 1828] [client ::1:61205] PHP Fatal error:  Uncaught Error: Attempt to modify property "value" on null in C:\\xampp\\htdocs\\ojs\\cache\\t_compile\\f09822d526ba2b77dee1b6fa34cba9dcc80abebc^756a7119cb48731a8fd45c250b45f4bcca2d6b01_0.app.frontendpagessearch.tpl.php:51\nStack trace:\n#0 C:\\xampp\\htdocs\\ojs\\lib\\pkp\\lib\\vendor\\smarty\\smarty\\libs\\sysplugins\\smarty_template_resource_base.php(123): content_610104fa1e78c7_34821107(Object(Smarty_Internal_Template))\n#1 C:\\xampp\\htdocs\\ojs\\lib\\pkp\\lib\\vendor\\smarty\\smarty\\libs\\sysplugins\\smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))\n#2 C:\\xampp\\htdocs\\ojs\\lib\\pkp\\lib\\vendor\\smarty\\smarty\\libs\\sysplugins\\smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))\n#3 C:\\xampp\\htdocs\\ojs\\lib\\pkp\\lib\\vendor\\smarty\\smarty\\libs\\sysplugins\\smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 1)\n#4 C:\\xampp\\htdocs\\ojs\\lib\\pkp\\lib\\vendor\\smarty\\smarty\\libs\\sysplugins\\smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, 'f09822d526ba2b7...', NULL, 1)\n#5 C:\\xampp\\htdocs\\ojs\\lib\\pkp\\classes\\template\\PKPTemplateManager.inc.php(1187): Smarty_Internal_TemplateBase->display('frontend/pages/...', NULL, 'f09822d526ba2b7...', NULL)\n#6 C:\\xampp\\htdocs\\ojs\\pages\\search\\SearchHandler.inc.php(149): PKPTemplateManager->display('frontend/pages/...')\n#7 C:\\xampp\\htdocs\\ojs\\pages\\search\\SearchHandler.inc.php(38): SearchHandler->search(Array, Object(Request))\n#8 C:\\xampp\\htdocs\\ojs\\lib\\pkp\\classes\\core\\PKPRouter.inc.php(395): SearchHandler->index(Array, Object(Request))\n#9 C:\\xampp\\htdocs\\ojs\\lib\\pkp\\classes\\core\\PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)\n#10 C:\\xampp\\htdocs\\ojs\\lib\\pkp\\classes\\core\\Dispatcher.inc.php(144): PKPPageRouter->route(Object(Request))\n#11 C:\\xampp\\htdocs\\ojs\\lib\\pkp\\classes\\core\\PKPApplication.inc.php(362): Dispatcher->dispatch(Object(Request))\n#12 C:\\xampp\\htdocs\\ojs\\index.php(68): PKPApplication->execute()\n#13 {main}\n  thrown in C:\\xampp\\htdocs\\ojs\\cache\\t_compile\\f09822d526ba2b77dee1b6fa34cba9dcc80abebc^756a7119cb48731a8fd45c250b45f4bcca2d6b01_0.app.frontendpagessearch.tpl.php on line 51, referer: http://localhost/ojs/index.php/snlg/index

![image](https://user-images.githubusercontent.com/87708319/127282647-c2621d28-fdf8-4887-af81-deaf3de37ed7.png)

Can you help me? thanks in advance

**Comment by bibliocoder** [comment]
Hi,
I was not able to reproduce the error you reported, could be related to the PHP version you are using, but due to time constraints I can't offer individual support. Please consult the [OJS Community Forum](https://forum.pkp.sfu.ca) for that.

Although I just released an [update for the lastest OJS version 3.3](https://github.com/nicolols/OJS-3-enhanced-advanced-search/releases/tag/v1.0.1) as I noticed that the OJS developers made significant changes to the search.tpl. Consider trying that version, maybe it will also help to fix your issue.

Have a nice day!

**Comment by weroiss** [comment]
Hi, 
your new release fixed my problem.
thanks!!!
